// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
)

const detailusers = `-- name: Detailusers :one
SELECT id, name, email, address, "phone" FROM users
WHERE id = $1
ORDER BY name
`

func (q *Queries) Detailusers(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, detailusers, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Address,
		&i.Phone,
	)
	return i, err
}

const listusers = `-- name: Listusers :many
SELECT id, name, email, address, "phone" FROM users
ORDER BY name
`

func (q *Queries) Listusers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listusers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Address,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
